name: Docker Images Builder

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

env:
  GHCR_IMAGE_NAME: kazik117/alpine-android-python
  DEFAULT_JDK_VERSION: 17
  LATEST_STABLE_API: 33

jobs:
  build_base_images:
    name: Build Alpine Android Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        android-api: [33]
        jdk: [17]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables
        shell: sh
        run: |
          set -eu

          case ${{ matrix.jdk }} in
              8)
                CMDLINE_VERSION="8.0"
                SDK_TOOLS_VERSION="9123335" ;;
              *)
                CMDLINE_VERSION="9.0"
                SDK_TOOLS_VERSION="9477386" ;;
          esac
          case ${{ matrix.android-api }} in
              33) BUILD_TOOLS_VERSION="33.0.2" ;;
          esac
          echo "BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION" >> $GITHUB_ENV
          echo "CMDLINE_VERSION=${CMDLINE_VERSION}" >> $GITHUB_ENV
          echo "SDK_TOOLS_VERSION=${SDK_TOOLS_VERSION}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}
          tags: |
            type=raw,value=android-${{ matrix.android-api }}-jdk${{ matrix.jdk }}
            type=raw,value=android-${{ matrix.android-api }}-jdk${{ matrix.jdk }}-${{ github.ref_name }},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=android-${{ matrix.android-api }},enable=${{ matrix.jdk == env.DEFAULT_JDK_VERSION }}
            type=raw,value=latest-jdk${{ matrix.jdk }},enable=${{ matrix.android-api == env.LATEST_STABLE_API }}
            type=raw,value=latest,enable=${{ matrix.android-api == env.LATEST_STABLE_API && matrix.jdk == env.DEFAULT_JDK_VERSION }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build Android API ${{ matrix.android-api }} JDK${{ matrix.jdk }}
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/android.Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JDK_VERSION=${{ matrix.jdk }}
            CMDLINE_VERSION=${{ env.CMDLINE_VERSION }}
            SDK_TOOLS_VERSION=${{ env.SDK_TOOLS_VERSION }}
            BUILD_TOOLS=${{ env.BUILD_TOOLS_VERSION }}
            TARGET_SDK=${{ matrix.android-api }}